# Copyright 2023 Google LLC
#
# This is “Software” that is licensed under the “General Software” section of
# the Service Specific Terms (https://cloud.google.com/terms/service-terms) for
# usage in accordance with the following “Scope of Use”: This file may only be
# used on an Anthos cluster, including any associated ci/cd use. “Anthos
# cluster” is defined as “A Cluster (of any kind) registered to a fleet project
# where the Anthos API is enabled”.
apiVersion: constraints.gatekeeper.sh/v1beta1
kind: K8sPSPAllowedUsers
metadata:
  name: cis-gke-v1.4.0-restrict-root-containers
  labels:
    policycontroller.gke.io/bundleName: cis-gke-v1.4.0
  annotations:
    policycontroller.gke.io/bundleVersion: 202310.0-preview
    policycontroller.gke.io/constraintData: |-
      "{
        bundleName: 'cis-gke-v1.4.0',
        bundleDisplayName: 'CIS GKE Benchmark v1.4.0',
        bundleLink: 'https://github.com/GoogleCloudPlatform/acm-policy-controller-library/tree/master/anthos-bundles/cis-gke-v1.4.0',
        bundleVersion: '202310.0-preview',
        bundleDescription: 'Use the CIS GKE Benchmark 1.4.0 policy bundle with Policy Controller to evaluate the compliance of your cluster resources against the CIS GKE Benchmark v1.4.0, which is a set of recommendations for configuring GKE to support a robust security posture.',
        controlNumbers: '[4.2.6,5.10.3]',
        severity: 'UNSPECIFIED',
        description: 'Restricts containers from running as the root user.',
        remediation: 'Containers cannot run with `runAsUser` set to `root`. Set your containers with `runAsUser: ` to a non-root user ID. See "Set the security context for a Pod" for more information: https://kubernetes.io/docs/tasks/configure-pod-container/security-context/#set-the-security-context-for-a-pod',
        minimumTemplateLibraryVersion: '1.11.1'
      }"
spec:
  enforcementAction: dryrun
  match:
    kinds:
    - apiGroups:
      - ""
      kinds:
      - Pod
    excludedNamespaces:
    - kube-system
    - asm-system
    - config-management-system
    - cert-manager
    - anthos-identity-service
    - apigee
  parameters:
    runAsUser:
      rule: MustRunAsNonRoot
    exemptImages:
    - gcr.io/gke-release/asm/proxyv2:*
    - gcr.io/anthos-baremetal-release/*
    - gke.gcr.io/*
